{
    {
        int a, b
        a = 1; b = 1
        System.out.println(a == b)
        System.out.println(a != b)
        System.out.println(a is b)
        System.out.println(a is not b)
    }
    System.out.println()
    {
        int a, b
        a = 1; b = a
        System.out.println(a == b)
        System.out.println(a != b)
        System.out.println(a is b)
        System.out.println(a is not b)
    }
}
